apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop-mongodb
    environment: dev
    tier: database
spec:
  replicas: 1
  matchLabels:
     project: roboshop-mongodb
     environment: dev
     tier: database
  containers:
  - name: mongodb
    image: sivpri/mongodb    
