apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb-deployment
  labels:
    tier: database
    project: roboshop
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
      project: roboshop
      env: dev 
  template:
    metadata:
      name: mongodb
      labels:
        tier: database
        project: roboshop
        env: dev  
    spec:
      containers:
      - name: mongodb
        iamge: sivpri/mongodb:v1        