apiVersion: apps/v1
kind: Deployment
matadata: 
  namepsace: roboshop
  name: catalogue
  labels:
    purpose: catalogue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      projectname: roboshop
      categiry: catalogue
      tier: app
      env: dev    
  template:
    metadata:
      name: catalogue
      labels:
        projectname: roboshop
        categiry: catalogue
        tier: app
        env: dev
    spec:
      containers:
      - name: catalogue
        image: sivpri/catalogue:v1       

---

apiVersion: v1
kind: Service
metadata:
  namepsace: roboshop
  name: catalogue
  labels:
    name: catalogue
spec:
  selector:    
    projectname: roboshop
    categiry: catalogue
    tier: app
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080  