apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    category: cart
    tier: database
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      category: cart
      tier: database
      environment: dev
template:
  metadata:
    labels:
      project: roboshop
      category: cart
      tier: database
      environment: dev
  spec: 
    containers:
    - name: redis
      image: redis:7.0

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    category: cart
    tier: database
    environment: dev
spec:
  selector:
    project: roboshop
    category: cart
    tier: database
    environment: dev 
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

    